version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: neopro
      MONGO_INITDB_ROOT_PASSWORD: 123456

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: neopro
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://neopro:123456@mongo:27017/

  backend:
    build: .
    ports:
      - 3001:3001
    environment:
      PORT: 3001
      DB_NAME: neopro
      DB_HOST: mongo
      DB_PORT: 27017
      DB_USER: neopro
      DB_PASS: 123456
